version: "2"

services:

  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=adminadmin
    volumes:
      - mysql-drop:/var/lib/mysql
      - /Users/dev/Documents/mysqlInit:/docker-entrypoint-initdb.d/:ro
    ports:
      - "3306:3306"

  project:
    container_name: docker-dropwizard
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - "8090:8090"
      - "8091:8091"
    tty: true

volumes:
  mysql-drop: